name: PHPUnit Test and PHPCS check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: phpcs, phpunit

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: phpunit --coverage-clover ./clover.xml
    
    - name: Upload coverage
      run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r clover.xml
      env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_TOKEN }}

    - name: Check code style
      run: phpcs
